language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - iverilog

install:
- pip install pytest

script:
- pytest test_main.py ./test/test_bit_vector.py ./test/test_floating_point.py ./test/test_cube.py ./test/test_divider.py
